# Generated by Django 4.0.4 on 2022-05-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100, verbose_name='Name')),
                ('email_address', models.CharField(max_length=100, null=True, unique=True, verbose_name='Email Address')),
                ('age', models.PositiveIntegerField(null=True, verbose_name='Age')),
                ('birthday', models.DateTimeField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('member_join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_year', models.IntegerField()),
                ('movie_genere', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.members', verbose_name='Member Name')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies', verbose_name='Movie Name')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies'),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
