# Generated by Django 4.0.4 on 2022-05-18 23:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_members_movies_movie_rental_alter_comment_movie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Age')),
                ('imageURL', models.ImageField(upload_to='actors/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('imageURL', models.ImageField(upload_to='movies/', verbose_name='Poster')),
                ('date_of_realise', models.DateTimeField(default=datetime.date.today, verbose_name='realise date')),
                ('url', models.SlugField(max_length=150, unique=True)),
                ('actors', models.ManyToManyField(related_name='film_actor', to='movie.actor', verbose_name='actor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.category', verbose_name='Category')),
                ('genres', models.ManyToManyField(to='movie.genre', verbose_name='Genres')),
                ('producers', models.ManyToManyField(related_name='film_director', to='movie.actor', verbose_name='producer')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='MoviePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Pictures')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'Movie picture',
                'verbose_name_plural': 'Movie pictures',
            },
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='movie.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'rating',
            },
        ),
        migrations.CreateModel(
            name='StarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Star',
                'verbose_name_plural': 'Stars',
            },
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.comment', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default='some text', max_length=500, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='some name', max_length=100, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='Movie_Rental',
        ),
        migrations.AddField(
            model_name='movierating',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.starrate', verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
