# Generated by Django 4.0.4 on 2022-05-19 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_actor_category_genre_movie_moviepictures_movierating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='movie'),
        ),
    ]
