# Generated by Django 4.0.4 on 2022-05-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movierating_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
