# Generated by Django 4.0.4 on 2022-05-23 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_of_realise',
        ),
        migrations.AddField(
            model_name='movie',
            name='date_of_release',
            field=models.DateField(default=datetime.date.today, verbose_name='release date'),
        ),
    ]
