# Generated by Django 4.0.4 on 2022-05-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_movie_date_of_realise_movie_date_of_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.member', verbose_name='Member Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='moviepictures',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='producers',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='genre', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='MoviePictures',
        ),
        migrations.DeleteModel(
            name='MovieRating',
        ),
        migrations.DeleteModel(
            name='StarRate',
        ),
        migrations.AddField(
            model_name='movierental',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='Movie Name'),
        ),
    ]
