# Generated by Django 3.2 on 2022-06-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AlterField(
            model_name='actor',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to='actors/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='Poster'),
        ),
    ]
