# Generated by Django 4.0.4 on 2022-06-04 11:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_actor_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='imageURL',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imageURL'),
        ),
    ]
