# Generated by Django 4.0.4 on 2022-06-04 11:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_actor_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imageURL',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imageURL'),
        ),
    ]
